### ISSUE TITLE
excellent works!

### ISSUE THREAD

**Issue by berli** [tzutalin/dlib-android-app#1]
I always want to port dlib to android , so that we can enjoy powerful ability of detecting  person and face of dlib when driving; it can alarm by audio or flashing when detected a persion in front of the car!

I found the app havn't geting image from the camera to real time detecting;
but I am expect in C++,C not java, hope you realize the function

**Comment by tzutalin** [comment]
Hi @berli 
 In fact, it's not difficult. It needs to take time to realize it. However, I am studying another project TensorFlow, I will realize the features when I have free time. You can try it to implement it by yourself and send a pull-request.

My another repository can detect any object using fastRCNN and CNN, but it needs to speed up. 
https://github.com/tzutalin/Android-Object-Detection
