### ISSUE TITLE
Wrong initialization of VisionDetRet class

### ISSUE THREAD

**Issue by beraldofilippo** [tzutalin/dlib-android-app#12]
Forgot to initialize correctly `ArrayList<Point>` in `VisionDetRet`.

The default constructor should be
`VisionDetRet() {
        mLandmarkPoints = new ArrayList<>();
    }` insted of being completely empty.

Alternatively you can add the initialization right into the private field declaration.
Sorry for that it slipped away!

**Comment by tzutalin** [comment]
Thx. Don't worry about it. I have initialized the private filed, you can check the source code. :)
