### ISSUE TITLE
ExternalSystemException: String index out of range: -115

### ISSUE THREAD

**Issue by msecilmis** [tzutalin/dlib-android-app#13]
When I try to run the program on android studio 2.0, it always gives this issue.
Any idesa?

**Comment by tzutalin** [comment]
Could you provide me with more details?

Do you mean you are trying to build app using AndroidStudio, it will have an error at the compile time?

**Comment by msecilmis** [comment]
It was at compile time. The problem solved with     
lintOptions {
        checkReleaseBuilds false
    }
at gradle

Thanks
