### ISSUE TITLE
it always crash !

### ISSUE THREAD

**Issue by berli** [tzutalin/dlib-android-app#2]
it always crash after I select one picture, any picture!
when I runing it as debug mode, I saw it is keep the "Person and face detection", lasting few minutes , it stop working..

**Comment by tzutalin** [comment]
Any logs?

**Comment by berli** [comment]
11-22 22:31:30.740 31614-31614/com.tzutalin.dlibtest W/dalvikvm: VFY: unable to resolve direct method 17839: Landroid/widget/LinearLayout$LayoutParams;.<init> (Landroid/widget/LinearLayout$LayoutParams;)V
11-22 22:31:43.080 31614-31951/com.tzutalin.dlibtest E/People_Det-JNI: JNI On Load
11-22 22:31:43.080 31614-31951/com.tzutalin.dlibtest W/dalvikvm: Exception Ljava/lang/NoSuchFieldError; thrown while initializing Lcom/tzutalin/dlib/PeopleDet;
11-22 22:31:43.080 31614-31951/com.tzutalin.dlibtest W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x41b1d930)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager: Activity com.tzutalin.dlibtest.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4237aa28 V.E..... R......D 0,0-684,324} that was originally added here
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager: android.view.WindowLeaked: Activity com.tzutalin.dlibtest.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4237aa28 V.E..... R......D 0,0-684,324} that was originally added here
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:382)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:219)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.Dialog.show(Dialog.java:281)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ProgressDialog.show(ProgressDialog.java:116)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ProgressDialog.show(ProgressDialog.java:99)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at com.tzutalin.dlibtest.MainActivity$DetTask.onPreExecute(MainActivity.java:112)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.os.AsyncTask.execute(AsyncTask.java:534)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at com.tzutalin.dlibtest.MainActivity.onActivityResult(MainActivity.java:238)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.Activity.dispatchActivityResult(Activity.java:5441)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3366)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3413)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.access$1100(ActivityThread.java:145)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.os.Looper.loop(Looper.java:137)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.main(ActivityThread.java:5117)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at java.lang.reflect.Method.invokeNative(Native Method)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at java.lang.reflect.Method.invoke(Method.java:511)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
11-22 22:31:44.020 31614-31614/com.tzutalin.dlibtest E/WindowManager:     at dalvik.system.NativeStart.main(Native Method)

**Comment by tzutalin** [comment]
Hi @berli 
  Could you pull again and re-build it? What's your  Android API version?

Otherwise, you can install the apk directly to try.
https://github.com/tzutalin/dlib-android-app/tree/master/demo

`$ adb install app-debug.apk`

**Comment by berli** [comment]
@tzutalin  I modify the miniSdkVersion from default vaue:21 to 17, because the version of the Android on my phone is 4.2, as following:

   defaultConfig {
        minSdkVersion 17
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

**Comment by tzutalin** [comment]
@berli 
Is it ok?

**Comment by berli** [comment]
@tzutalin 
it is still crash, log as following...
11-24 21:19:35.410 27893-28789/com.tzutalin.dlibtest E/People_Det-JNI: JNI On Load
11-24 21:19:35.410 27893-28789/com.tzutalin.dlibtest W/dalvikvm: Exception Ljava/lang/NoSuchFieldError; thrown while initializing Lcom/tzutalin/dlib/PeopleDet;
11-24 21:19:35.410 27893-28789/com.tzutalin.dlibtest W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x41b1d930)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager: Activity com.tzutalin.dlibtest.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42315a48 V.E..... R......D 0,0-684,324} that was originally added here
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager: android.view.WindowLeaked: Activity com.tzutalin.dlibtest.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42315a48 V.E..... R......D 0,0-684,324} that was originally added here
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:382)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:219)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.Dialog.show(Dialog.java:281)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ProgressDialog.show(ProgressDialog.java:116)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ProgressDialog.show(ProgressDialog.java:99)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at com.tzutalin.dlibtest.MainActivity$DetTask.onPreExecute(MainActivity.java:112)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.os.AsyncTask.execute(AsyncTask.java:534)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at com.tzutalin.dlibtest.MainActivity.onActivityResult(MainActivity.java:238)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.Activity.dispatchActivityResult(Activity.java:5441)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3366)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3413)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.access$1100(ActivityThread.java:145)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.os.Looper.loop(Looper.java:137)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at android.app.ActivityThread.main(ActivityThread.java:5117)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at java.lang.reflect.Method.invokeNative(Native Method)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at java.lang.reflect.Method.invoke(Method.java:511)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
11-24 21:19:37.130 27893-27893/com.tzutalin.dlibtest E/WindowManager:     at dalvik.system.NativeStart.main(Native Method)

**Comment by tzutalin** [comment]
It's wierd. It's ok on Android L and M. It should be the issue with your device version

**Comment by berli** [comment]
the Android version is 4.2.2, I must rebuild it so that can install;
the log is same as the previous source;

**Comment by tzutalin** [comment]
@berli 
I know the root cause. Your API level should be 21 or later becuase I set min API level in JNI. Please refer to 
https://github.com/tzutalin/dlib-android/blob/master/jni/Application.mk

**Comment by berli** [comment]
1 NDK_TOOLCHAIN_VERSION := 4.9                                                                                                                          
  2 #APP_PLATFORM := android-21
  3 APP_PLATFORM := android-17
  4 APP_STL := gnustl_static
  5 APP_ABI := armeabi-v7a x86 x86_64#armeabi #all
  6 APP_MODULE := libdlib

@tzutalin, I set the APP_PLATFORM := android-17, as above, and rebuild the libpeople_det.so, it always crash! log is same as the previous!
