### ISSUE TITLE
how to fix the crash on miniSdkVersion 17

### ISSUE THREAD

**Issue by berli** [tzutalin/dlib-android-app#3]
1 NDK_TOOLCHAIN_VERSION := 4.9                                                                                                                          
  2 #APP_PLATFORM := android-21
  3 APP_PLATFORM := android-17
  4 APP_STL := gnustl_static
  5 APP_ABI := armeabi-v7a x86 x86_64#armeabi #all
  6 APP_MODULE := libdlib

@tzutalin, I set the APP_PLATFORM := android-17, as above, and rebuild the libpeople_det.so, it always crash! log is same as the previous!
https://github.com/tzutalin/dlib-android-app/issues/2

**Comment by berli** [comment]
it must require android-21, Is there any solution to figure out the root cause?
your taipei, I mainland~~
we should figure out the root cause to run it on more android device

**Comment by tzutalin** [comment]
@berli ,
Ok. I will try after I get android paltform with KK version

**Comment by berli** [comment]
any progress ?

**Comment by berli** [comment]
@tzutalin any progress ?

**Comment by tzutalin** [comment]
@berli 
Sorry. I did not get the platform with KK version.
