### ISSUE TITLE
Can I use the package 'dlib' in other project? 

### ISSUE THREAD

**Issue by YuGongCharley** [tzutalin/dlib-android-app#49]
Can I use the package 'dlib' in other project? thx

**Comment by tzutalin** [comment]
Sure. You can

**Comment by YuGongCharley** [comment]
@tzutalin I have a problem when I use the package 'dlib' in my project :
Cannot resolve corresponding JNI function Java_com_tzutalin_dlib_FaceDet_jniNativeClassInit
Cannot resolve corresponding JNI function Java_com_tzutalin_dlib_FaceDet_jniInit
Cannot resolve corresponding JNI function Java_com_tzutalin_dlib_FaceDet_jniDeInit
Cannot resolve corresponding JNI function Java_com_tzutalin_dlib_FaceDet_jniBitmapDetect
Cannot resolve corresponding JNI function Java_com_tzutalin_dlib_FaceDet_jniDetect

I need some help plz
