### ISSUE TITLE
Error:Execution failed for task ':dlib:ndkBuild'.

### ISSUE THREAD

**Issue by piweihwt** [tzutalin/dlib-android-app#6]
import to Android Studio it will show this error:

is there any thing wrong of my env.

Error:Execution failed for task ':dlib:ndkBuild'.
> A problem occurred starting process 'command 'idk-build''

**Comment by tzutalin** [comment]
Ya. There are some issues about using Android studio's gradle to build. I will fix the gradle in few days.



You can use the command as bellows to build first, and uncomment ndk-build in dlib's gradile.

$ cd dlib-android-app/dlib/src/main/dlib
$ ndk-build -j8
copy *.so to lib-android-app/dlib/src/main/jniLibs

**Comment by tzutalin** [comment]
@piweihwt 
  I figure out your problem. The root cause is that your Android stduio did not find nkd-build command.

One of solutions:
Add ndk.dir=[YOUR_NDK_FOLDER] in local.prperties
