### ISSUE TITLE
slow facial landmarks detection

### ISSUE THREAD

**Issue by chrysantd** [tzutalin/dlib-android-app#9]
Thanks for your great work. It is very useful. However, when I tried demo app to detect facial landmarks, it took more than 10s to finish the whole process for only one picture. Is there any configurations I need to notice? Or it is the normal speed?

**Comment by tzutalin** [comment]
Hi,
  How did you profile? What is your image resolution?

Except to facial landmark, I also do HOG Opencv detection before doing
facial landmark.

Regards,
TzuTa lin

Thanks for your great work. It is very useful. However, when I tried demo
app to detect facial landmarks, it took more than 10s to finish the whole
process for only one picture. Is there any configurations I need to notice?
Or it is the normal speed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/tzutalin/dlib-android-app/issues/9>

**Comment by chrysantd** [comment]
It is a 250*250 jpeg image. Another problem, I trained a 15-points model, and change the path in getFaceShapeModelPath() function, but it still uses the 68-point model...

**Comment by tzutalin** [comment]
Hi @chrysantd ,
  After check, it takes 3~4 seconds to load model for the first time.

Then, usually, it takes 1~2 seconds detect face and landmark for 225x225 images.

First time:
```
01-02 21:26:23.286  5034  5232 I native  : I/jni_people_det.cpp:306 com_tzutalin_dlib_PeopleDet jniDLibHOGFaceDetect
..
01-02 21:26:28.427  5034  5232 I native  : I/jni_people_det.cpp:147 Dlib HOG face det size : 1
01-02 21:26:28.434  5034  5232 I native  : I/jni_people_det.cpp:153 face index:0number of parts: 68
```
Second time:
```
8.055  5034  5232 I native  : I/jni_people_det.cpp:306 com_tzutalin_dlib_PeopleDet jniDLibHOGFaceDetect
...
01-02 21:31:49.541  5034  5232 I native  : I/jni_people_det.cpp:147 Dlib HOG face det size : 1
01-02 21:31:49.548  5034  5232 I native  : I/jni_people_det.cpp:153 face index:0number of parts: 68
```

In general, it should load the model according getFaceShapeModelPath(). Can you share with me about how you do that? I can help you to verify your model.

**Comment by tzutalin** [comment]
@chrysantd ,
 Could you share your model to this repository?

**Comment by bpkrishnan** [comment]
The default shape_predictor_68_face_landmarks.dat itself is taking 10sec to load initaly. What to do?

**Comment by gerardsimons** [comment]
I am also facing this latency issue. Is it possible to keep the model in memory some how?

**Comment by Andiseetu** [comment]
Hi, shape_predictor_68_face_landmarks.dat gallery image its taking 10-15 secs, camera activity facing issue running background threads to capture and convert, will u share me the perfect procedure for live camera preview frames?

**Comment by WaqarAhmadAwan** [comment]
Hello I got 3 points of mouth and now i want to change mouth means lips colors or adding lips image so user can see how other colors looks on his / her lips kindly guide me if any one have idea your response will be much appreciated.
Thanks
